/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CatBtn: typeof import('./../components/CatBtn.vue')['default']
    CatSpin: typeof import('./../components/CatSpin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAvatar: typeof import('./../components/TheAvatar.vue')['default']
    TheInput: typeof import('./../components/TheInput.vue')['default']
  }
}
